# N-D Array Operator

In [1]:
import numpy as np

## 逐元計算 (elementwise)
- 前提：陣列維度需要相等

In [2]:
data_1 = np.array([1 ,2 ,3])
data_2 = np.array([4 ,5 ,6])
print("data_1 =", data_1)
print("data_2 =" ,data_2)
result = None

data_1 = [1 2 3]
data_2 = [4 5 6]


### add

In [3]:
result = data_1 + data_2
print("data_1 + data_2 =" ,result)

data_1 + data_2 = [5 7 9]


### times

In [4]:
result = data_1 * data_2
print("data_1 * data_2 =", result)

data_1 * data_2 = [ 4 10 18]


### bigger

In [5]:
result = data_1 > data_2
print("data_1 > data_2 =", result)

data_1 > data_2 = [False False False]


### equal

In [6]:
result + data_1 == data_2
print("data_1 == data_2 =", result)

data_1 == data_2 = [False False False]


## 矩陣計算 (matrix)

In [7]:
data_3 = np.array([
    [1 ,2]
]) # 1*2
data_4 = np.array([
    [1, 2, 3],
    [2, 3, 4]
]) # 2*3
print("data_3 =" ,data_3)
print("data_4 =" ,data_4)
result = None

data_3 = [[1 2]]
data_4 = [[1 2 3]
 [2 3 4]]


### dot

In [8]:
result = data_3.dot(data_4)
print("data_3 dot data_4 =", result)
result = data_3@data_4
print("data_3 dot data_4 =", result)

data_3 dot data_4 = [[ 5  8 11]]
data_3 dot data_4 = [[ 5  8 11]]


### cross

In [9]:
result = np.outer(data_3 ,data_4)
print("data_3 cross data_4 =", result)

data_3 cross data_4 = [[1 2 3 2 3 4]
 [2 4 6 4 6 8]]


## 統計計算 (statistics)

In [10]:
data_5 = np.array([
    [1, 2, 3],
    [4 ,5 ,6]
])
print("data_5 =",data_5)
result = None

data_5 = [[1 2 3]
 [4 5 6]]
