# N-D Array Shape

In [24]:
import numpy as np

## Basic

In [25]:
data_1 = np.ones(10)
print("data_1 shape =", data_1.shape)

data_1 shape = (10,)


In [26]:
data_2 = np.ones([2 ,3])
print("data_2 shape =" ,data_2.shape)

data_2 shape = (2, 3)


## Rotate

In [27]:
data_3 = np.array([
    [1, 2, 3],
    [4 ,5 ,6]
])
print("data_3 data:")
print(data_3)

print("data_3 shape =" ,data_3.shape ,"\n")


print("Rotated data_3 data:")
print(data_3.T)
print("Rotated data_3 shape =",data_3.T.shape)


data_3 data:
[[1 2 3]
 [4 5 6]]
data_3 shape = (2, 3) 

Rotated data_3 data:
[[1 4]
 [2 5]
 [3 6]]
Rotated data_3 shape = (3, 2)


## Reduce Degree - ravel()

In [28]:
data_4 = np.array([
    [
        [1 ,2] ,[2 ,3]
    ],
    [
        [3 ,4] ,[4 ,5]
    ]
])
print("data_4 data:")
print(data_4)
print("data_4 shape =" ,data_4.shape ,"\n")
data_5 = data_4.ravel()
print("raveled data_4:")
print(data_5)

data_4 data:
[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
data_4 shape = (2, 2, 2) 

raveled data_4:
[1 2 2 3 3 4 4 5]


## 重塑資料形狀

In [29]:
data_4 = np.array([
    [
        [1 ,2] ,[2 ,3]
    ],
    [
        [3 ,4] ,[4 ,5]
    ]
]) # 2 * 2 * 2
print("data_4 data:")
print(data_4)
print("data_4 shape =" ,data_4.shape ,"\n")

data_6 = data_4.reshape(2 ,4) # 2 * 4 = 2 * 2 * 2
print("Reshaped data_4:")
print(data_6)
print("data_6 shape =" ,data_6.shape ,"\n")

data_4 data:
[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
data_4 shape = (2, 2, 2) 

Reshaped data_4:
[[1 2 2 3]
 [3 4 4 5]]
data_6 shape = (2, 4) 



In [30]:
data_7 = np.arange(1 ,11 ,1).reshape(2, 5)
print("data_7:\n", data_7)

data_7:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
